apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    application: logstash
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 9200
      protocol: TCP
      name: tcp0
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: tcp1
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: tcp2
    - port: 5003
      targetPort: 5003
      protocol: TCP
      name: tcp3
    - port: 5004
      targetPort: 5004
      protocol: TCP
      name: tcp4
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: tcp5
  selector:
    application: logstash
