apiVersion: v1
kind: Service
metadata:
  name: storm-supervisor
  labels:
    application: storm-supervisor
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: http
  selector:
    application: storm-supervisor
