apiVersion: v1
kind: Service
metadata:
  name: storm-ui
  labels:
    application: storm
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    application: storm
    component: ui
