apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    application: elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: serving
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: node2node
  selector:
    application: elasticsearch
