apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    application: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: 2181
      protocol: TCP
      name: http
  selector:
    application: zookeeper
