apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    application: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    application: kibana
